dist: xenial
language: haskell
cabal: "2.4"
addons:
  apt:
    packages:
      - libglfw3-dev
ghc:
  - "8.0"
  - "8.2"
  - "8.4"
  - "8.6"
before_install:  # remove this when GPipe > 2.2.4 is on hackage
  - git clone https://github.com/tobbebex/GPipe-Core.git
  - cd ./GPipe-Core
  - cabal v2-install all
  - cd ..
install:
  - cabal v2-build all --only-dependencies
script:
  - cabal v2-build all
